# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8780e3527191485c6b3fa0a67812cff5bcb074f0c2ee65f3cad94ea6f19d5648e53e2d32e013d77bc47dfe1afbf2f0ca157ed423098b54bfe171f5f75c92f34d

test:
  secret_key_base: b72f54c909f16397d974597148f5f4a04239edaad470ac3216f9c8297e7422ea2487dadb89b7bfdcd44757c012744150e868118ed33ba9cfbc854fd71a392e43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
